#!/bin/bash

# *************************************************
# javac-algs4
# Hayk Martirosyan
# -------------------
# Wrapper for javac that includes algs4 libraries.
# *************************************************

# This must match the install directory
INSTALL=~/Dev/algs4
CLASSPATH=${INSTALL}/validation/bin

# Sets the path to the classpath libraries
jars=(${INSTALL}/lib/stdlib.jar:${INSTALL}/lib/algs4.jar:.)

javac -cp "$jars" -g -encoding UTF-8 "$@" -d "$CLASSPATH"
